# Generated by Django 4.0.2 on 2022-11-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('timein', models.DateTimeField(auto_now_add=True)),
                ('timeout', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annoucement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('isApproved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drainage',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('shape', models.CharField(max_length=50)),
                ('waterlevel', models.IntegerField()),
                ('blockage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
